### ISSUE TITLE
Not work with Card

### ISSUE THREAD

**Issue by shartoo** [amendx/vue-dndrop#17]
Example code as https://amendx.github.io/vue-dndrop/guide/using-vue.html#simple-component works fine,but if the code area 

``` 
<div class="draggable-item">
              {{item.data}}
            </div>
````

was replaced by 

```
<div class="draggable-item">
        <q-card>
           .........
     </q-card>
    </div>
```

nothing will show

**Comment by amendx** [comment]
Hi, if maybe you're using `vue3`, try updating the package to `vue-dndrop@next` and see if that problem goes away.

**Comment by shartoo** [comment]
My bad,it's OK now,thank you!
