### ISSUE TITLE
Vue 3 - "createElement is not a function"

### ISSUE THREAD

**Issue by NeroN7F** [amendx/vue-dndrop#18]
Hi ! Just faced with problem when using vue 3 version of library. 

I've installed it using npm and copied one of example in my project

`npm i vue-dndrop@next`

But still no results. Getting same createElement error which is common for vue 2 library running on vue 3 

Would appreciate your help

**Comment by NeroN7F** [comment]
Just reviewed both branches and find out that 
`npm i vue-dndrop@next` and `npm i vue-dndrop` both installing same vue 2.0 module

**Comment by amendx** [comment]
Hi, @NeroN7F , try it out now. I just rebundled the rollup file, see if it works! 

> `npm i vue-dndrop@next` or `yarn add vue-dndrop@next`

**Comment by NeroN7F** [comment]
It's fine now. Thank you

**Comment by Jhomalex** [comment]
> Acabo de revisar ambas sucursales y descubrir que y ambas instalando el mismo módulo vue 2.0`npm i vue-dndrop@next``npm i vue-dndrop`

Thanks, you save my life UuU
