### ISSUE TITLE
Drag and drop not working quite right with allot of items

### ISSUE THREAD

**Issue by Alexandrea** [amendx/vue-dndrop#19]
I started to use vue-dndrop (vuejs v2) today
and on a page with like 4 or so items it worked perfectly however i notice it not working correctly. 
if there was allot more items on the page
it works for like the first 5 ish+- but does not work after that
![a6vWYLmhRK](https://user-images.githubusercontent.com/622983/142479822-a30cc925-a95b-4889-b085-1c9ab4aa4ec2.gif)
Any ideas?
Also like this notice how the top draging is like instant (close to each other) and the bottom one it opens like 2 cards above it already
![5rsl4vioK0](https://user-images.githubusercontent.com/622983/142480607-b44e7b58-179f-4f24-b380-a456f2f5ae7d.gif)
and proberbly because i have data in them so there bigger i can't drop them anymore cause they don't "open" up in my view

Is this issue with my style or how could i fix this?

Greetings

**Comment by amendx** [comment]
hi @Alexandrea, could you set up a sandbox/jsfiddle/codepen or so for me to see what might be the problem here?

**Comment by Alexandrea** [comment]
Hi its ok

its probably a conflict with one of the things i use maybe styling or so
but i started to use another drag component and i'm going to use that one, seems to work fine without any fancy openings but it works,
its faster then vue-dndrop (mostly because it does not copy what i'm draging) because the timelines per timeline has like between 700-2000 data of rows on them and becomes slugish ofc this is no fault of your component (and the issue is sort of still present without the timeline)

i also would not know how i could give you the code without giving you my whole site in the progress
because i'm fetching data from api website i'm making with it.
i also started working with Vue for only 2weeks now so i'm not familiar with it yet.
and also i'm using vuexy admin template witch is a payed product. it could just be the fault of them tho i do not know.

Greetings
