### ISSUE TITLE
Remove console.log in /dist

### ISSUE THREAD

**Issue by filipelinhares** [amendx/vue-dndrop#20]
Hi,

There is a `console.log('draggable info', draggableInfo.element);` in `vue-dndrop/dist/vue-dndrop.js:1913`.
Can you remove it or add a debug flag to disable in production?

Thanks in advanced!

**Comment by amendx** [comment]
@filipelinhares hi! what version are you currently using?

**Comment by filipelinhares** [comment]
Hi, I was using 1.1.8, I will update it to the latest version.

Thanks @amendx!
