### ISSUE TITLE
Not working in modal

### ISSUE THREAD

**Issue by phattanun** [amendx/vue-dndrop#22]
The library didn't work if putting it inside modal.

**Comment by amendx** [comment]
Hi, @phattanun can you show me an example of it? What's happening.

**Comment by Alloco225** [comment]
Hello, I am having the same problem, the drag n drop system works fine on normal pages 
but once inside modals :
- the draggable is offset from the mouse handle
- the @drop doesn't trigger when the draggable is dropped

Note that the code for the drag n drop system is the exact same
[Video Reference](https://drive.google.com/file/d/1ul-aO-ALrw2iaMguKhCVQdAmwu_gkjjt/view?usp=sharing)
