### ISSUE TITLE
Not working with Iframes

### ISSUE THREAD

**Issue by paleacci** [amendx/vue-dndrop#23]
A really very nice plugin, but it doesn't work in iframes. As soon as you drag an element into an iframe, the drag is blocked.
Inside an iframe nothing can be dragged.

`  <div class="frame">` 
        ` <iframe ref="iframe" @load="ready = true" src="about:blank" />` 
        ` <Teleport v-if="ready" :to="$refs.iframe.contentWindow.document.body">` 
            ` <div class="simple-page">` 
                ` <Container @drop="onDrop">` 
                  ` <Draggable v-for="item in items" :key="item .id">` 
                    ` <div class="draggable-item">` 
                     `  {{item .data}}` 
                    ` </div>` 
                  ` </Draggable>` 
                ` </Container>` 
            ` </div>` 
        ` </Teleport>` 
    ` </div>`

**Comment by amendx** [comment]
@paleacci hi, can you show me a sandbox of this problem? Might be that the draggable gets blocked for either the `Teleport`'s container, or some other event. 

Here you can see the [lifecycle](https://github.com/amendx/vue-dndrop#lifecycle) and what events are emitted (if you're listening to them) and check out what's missing. 

Let me know
