### ISSUE TITLE
Scroll to bottom when dragging

### ISSUE THREAD

**Issue by treeleaf** [amendx/vue-dndrop#24]
I love this library. I have a problem that I can not drag elements to the drop zone when I already have elements that have a big height. So that it requires to scroll down. 

It is also the same issue when there is a large number of elements where a page scroll is required to see the last element. Like the example https://amendx.github.io/vue-dndrop/examples/drag-class.html 
Try to drag the first element to the last position. 

I would believe that the auto-scroll functionality would handle it, but I don't see how it works. When I drag the element at the bottom of the viewport and the dropzone is below what is visible, then there is no scrolling. 

Any thoughts on a solution for this problem?

**Comment by amendx** [comment]
Hi, @treeleaf. Actually, there's always a way to scroll the elements: `controlling the parents height`. 

Check out https://amendx.github.io/vue-dndrop/examples/drag-class.html again, I've made a simple workaround on what you can do without actually changing the library. 

It's autoscrollable by _default_, all you have to do is set the boundries. 

Let me know if that works out for you!
