### ISSUE TITLE
@drop will return `element: null` if content inside Draggable wasn't wrapped in a tag.

### ISSUE THREAD

**Issue by ga676005** [amendx/vue-dndrop#30]
I found that if content inside `Draggable` is not wrapped inside a tag.
The element property of the returned object of @drop event will be null.
I think this could be mentioned in the doc somewhere.
```vue
<script setup>
function onDrop(dropResult) {
  console.log(dropResult); // { ..., element: null }
}
</script>

<template>
  <Container @drop="onDrop">
    <Draggable v-for="item in items" :key="item">
      {{ item.data  }} 
    </Draggable>
  </Container>
</template>
```
---
Easy to fix this with wrapping the content inside `Draggable`  in a tag
```vue
<Draggable v-for="item in items" :key="item">
  <div>
    {{ item.data }}
  </div>
</Draggable>
```

**Comment by amendx** [comment]
@ga676005 hi, I've updated the docs. Check out this [link](https://amendx.github.io/vue-dndrop/examples/simple-tagless.html)

**Comment by ga676005** [comment]
Awesome!
