### ISSUE TITLE
Item can be duplicated when should-accept-drop returns false on the "from" container

### ISSUE THREAD

**Issue by danivdwerf** [amendx/vue-dndrop#35]
When using multiple columns and one column returns false in the should-accept-drop hook, items in this column can be dragged into other columns and it won't be removed from the initial column. This problem can be seen in the [Example](https://amendx.github.io/vue-dndrop/examples/events.html).

Steps to reproduce:
1. Open https://amendx.github.io/vue-dndrop/examples/events.html
2. Add a column
3. Disable "Accept Drop" on the right column
4. Move an item from the right column to the left column.

The element will move to the new column but also stays put on the right one. I would expect that the element moves to the left column and disappears from the right one.

**Comment by HenftyKnight** [comment]
Hello 

> When using multiple columns and one column returns false in the should-accept-drop hook, items in this column can be dragged into other columns and it won't be removed from the initial column. This problem can be seen in the [Example](https://amendx.github.io/vue-dndrop/examples/events.html).
> 
> Steps to reproduce:
> 
>     1. Open https://amendx.github.io/vue-dndrop/examples/events.html
> 
>     2. Add a column
> 
>     3. Disable "Accept Drop" on the right column
> 
>     4. Move an item from the right column to the left column.
> 
> 
> The element will move to the new column but also stays put on the right one. I would expect that the element moves to the left column and disappears from the right one.

Did you ever got this fixed, I am having trouble with the same issue, but I was not able to fix it, if you can let me know if you fixed it and how you fixed it that'd be great!.

Thank you
Henfty
