### ISSUE TITLE
Vue 3 - "TypeError: createElement is not a function"

### ISSUE THREAD

**Issue by sterzuccio** [amendx/vue-dndrop#50]
I currently use Vue 3 and in my package.json I have `"vue-dndrop": "^ 1.2.2"`. After running the `npm update` command the component has stopped working and I always get this error: `"Uncaught (in promise) TypeError: createElement is not a function"`. What can this be due to?

**Comment by amendx** [comment]
@sterzuccio Hi, take a look [here](https://amendx.github.io/vue-dndrop/guide/installation.html#installation) and the [current version](https://www.npmjs.com/package/vue-dndrop) for vue3

**Comment by sterzuccio** [comment]
I had updated to the latest version but it gave me problems. I solved it by locking the version at 1.2.2
