### ISSUE TITLE
Bug: Latest version not working with Vue 3

### ISSUE THREAD

**Issue by avaschi** [amendx/vue-dndrop#55]
After upgrading from version 1.2.7 to 1.2.8 the libary isn't working anymore. I get the following error: 

![vue dndrop error](https://user-images.githubusercontent.com/43808841/175318996-ac09905b-ee12-48c7-8b2e-9cca80ab71b1.png)
 
For now, downgrading to 1.2.7 is fixing this.

**Comment by amendx** [comment]
@avaschi checkout the https://www.npmjs.com/package/vue-dndrop for the latest packages list, but here at https://amendx.github.io/vue-dndrop/guide/installation.html#installation you can see how does it work. 

The 1.2.7 is indeed the latest version for Vue3.

**Comment by avaschi** [comment]
It seems to be a problem with pnpm then, it upgraded automatically to the 1.2.8 version after running "pnpm install"
