### ISSUE TITLE
question: dropPlaceholder functionality

### ISSUE THREAD

**Issue by reppard** [amendx/vue-dndrop#57]
I'm working with vue-dndrop with Vue3. I have everything mostly working but I can't seem to style the drop placeholder. I've supplied a class with `dropPlaceHolderOptions` but the class doesn't seem to apply. I'm looking for a similar effect to the Card and Kanban examples where there is an bordered placeholder but all I get is a visibility hidden element.  The space is there but the styling isn't. Any suggestions on troubleshooting this?

**Comment by amendx** [comment]
Hi @reppard

In the [cards example](https://amendx.github.io/vue-dndrop/examples/cards.html), the desired effect of the placeholder can be achieved by the `dropPlaceHolderOptions`, but if I change that to:

```js
   dropPlaceholderOptions: {
        className: "amendx-preview",
        animationDuration: "150",
        showOnTop: true,
      },
```

Whereas in the css:
```css
.amendx-preview {
  background-color: blue;
  border: 2px dashed red;
  margin: 15px;
}
```

The element will be created with my new `amendx-preview`, but only if the css class is set to its visibility as **global**. Classes created within a 
```vue
<style scoped>
```
**Won't be accessible.** I'll try and fix that, but for now, a simple workaround would be for you to declare your class outside a scoped style, or set the class in the global scope of your project. Let me know if that works for now.
