### ISSUE TITLE
npm  package for Vue 3.x does not include utils

### ISSUE THREAD

**Issue by CultivateCreate** [amendx/vue-dndrop#76]
Installing npm package using:

`$ npm i vue-dndrop@next`

does not provide utils

**Comment by CultivateCreate** [comment]
There are multiple references to './utils' and './utils/helpers' in the examples and those paths don't exist? Am I missing something?

**Comment by amendx** [comment]
@CultivateCreate those are just utils for the documentation. You can find them [here](https://github.com/amendx/vue-dndrop/tree/master/src/utils/container)
