### ISSUE TITLE
Evento de click no card

### ISSUE THREAD

**Issue by fabioselau077** [amendx/vue-dndrop#86]
Olá Amanda, obrigado pelo pacote.

Uma coisa que notei (ou pelo menos n encontrei) é a ausencia do evento de click, quando o usuário clica em algum card, no meu contexto eu iria recuperar os eventos do card clicado e exibir em um modal.

Estou utilizando o exemplo do kanban como base

Tem esse evento de click? 

Como solução temporária, eu apenas coloquei um @click no <Draggable

**Comment by amendx** [comment]
@fabioselau077 ❇️ boa tarde ❇️ 

Você não acha que aqui caberia um [`@click.native`](https://yossiabramov.com/blog/the-native-event-modifier-in-vue-js)? 

Tenta ai e vê se é o que você estava buscando.

**Comment by fabioselau077** [comment]
> @fabioselau077 ❇️ boa tarde ❇️
> 
> Você não acha que aqui caberia um [`@click.native`](https://yossiabramov.com/blog/the-native-event-modifier-in-vue-js)?
> 
> Tenta ai e vê se é o que você estava buscando.

Isso mesmo, Amanda, é que pensei que teria outra forma, mas com o @click resolvi, obrigado.

Vou fechar a issue, abraços
